version: '3.8'

services:
  menu_app:
    container_name: menu_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG_FILE: "config.yaml"
    entrypoint: "./entrypoint.sh"
    volumes:
      - ./src:/usr/src/app/src/
    networks:
      - menu_network
    ports:
      - "8000:8000"
    depends_on:
      menu_redis:
        condition: service_healthy
      menu_postgres_db:
        condition: service_healthy

  menu_redis:
    container_name: menu_redis
    image: redis:7.0.8-alpine
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - menu_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 20s
      retries: 100

  menu_postgres_db:
    container_name: menu_postgres_db
    image: postgres:15.1-alpine
    volumes:
      - menu_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=my_menu
      - POSTGRES_USER=my_menu
      - POSTGRES_PASSWORD=my_menu
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - menu_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U my_menu" ]
      interval: 5s
      timeout: 20s
      retries: 100

networks:
  menu_network:
    name: menu_network

volumes:
  menu_postgres_data:
